package lexer


const chCode_0 = 0x30;
const chCode_1 = 0x31;
const chCode_2 = 0x32;
const chCode_3 = 0x33;
const chCode_4 = 0x34;
const chCode_5 = 0x35;
const chCode_6 = 0x36;
const chCode_7 = 0x37;
const chCode_8 = 0x38;
const chCode_9 = 0x39;

const chCodea = 0x61;
const chCodeb = 0x62;
const chCodec = 0x63;
const chCoded = 0x64;
const chCodee = 0x65;
const chCodef = 0x66;
const chCodeg = 0x67;
const chCodeh = 0x68;
const chCodei = 0x69;
const chCodej = 0x6A;
const chCodek = 0x6B;
const chCodel = 0x6C;
const chCodem = 0x6D;
const chCoden = 0x6E;
const chCodeo = 0x6F;
const chCodep = 0x70;
const chCodeq = 0x71;
const chCoder = 0x72;
const chCodes = 0x73;
const chCodet = 0x74;
const chCodeu = 0x75;
const chCodev = 0x76;
const chCodew = 0x77;
const chCodex = 0x78;
const chCodey = 0x79;
const chCodez = 0x7A;
const chCodeA = 0x41;
const chCodeB = 0x42;
const chCodeC = 0x43;
const chCodeD = 0x44;
const chCodeE = 0x45;
const chCodeF = 0x46;
const chCodeG = 0x47;
const chCodeH = 0x48;
const chCodeI = 0x49;
const chCodeJ = 0x4A;
const chCodeK = 0x4B;
const chCodeL = 0x4C;
const chCodeM = 0x4D;
const chCodeN = 0x4E;
const chCodeO = 0x4F;
const chCodeP = 0x50;
const chCodeQ = 0x51;
const chCodeR = 0x52;
const chCodeS = 0x53;
const chCodeT = 0x54;
const chCodeU = 0x55;
const chCodeV = 0x56;
const chCodeW = 0x57;
const chCodeX = 0x58;
const chCodeY = 0x59;
const chCodeZ = 0x5a;

const chCode_underscore = 0x5F;            // _
const chCode_dollar = 0x24;                // $
const chCode_ampersand = 0x26;             // &
const chCode_asterisk = 0x2A;              // *
const chCode_at = 0x40;                    // @
const chCode_backslash = 0x5C;             // \
const chCode_backtick = 0x60;              // `
const chCode_bar = 0x7C;                   // |
const chCode_caret = 0x5E;                 // ^
const chCode_closeBrace = 0x7D;            // }
const chCode_closeBracket = 0x5D;          // ]
const chCode_closeParen = 0x29;            // )
const chCode_colon = 0x3A;                 // :
const chCode_comma = 0x2C;                 // ;
const chCode_dot = 0x2E;                   // .
const chCode_doubleQuote = 0x22;           // "
const chCode_equals = 0x3D;                // =
const chCode_exclamation = 0x21;           // !
const chCode_greaterThan = 0x3E;           // >
const chCode_hash = 0x23;                  // #
const chCode_lessThan = 0x3C;              // <
const chCode_minus = 0x2D;                 // -
const chCode_openBrace = 0x7B;             // {
const chCode_openBracket = 0x5B;           // [
const chCode_openParen = 0x28;             // (
const chCode_percent = 0x25;               // %
const chCode_plus = 0x2B;                  // +
const chCode_question = 0x3F;              // ?
const chCode_semicolon = 0x3B;             // ;
const chCode_singleQuote = 0x27;           // '
const chCode_slash = 0x2F;                 // /
const chCode_tilde = 0x7E;                 // ~

const chCode_backspace = 0x08;             // \b
const chCode_formFeed = 0x0C;              // \f
const chCode_byteOrderMark = 0xFEFF;
const chCode_space = 0x20;
const chCode_newline = 0x0A;               // \n
const chCode_return = 0x0D;                // \r
const chCode_tab = 0x09;                   // \t
const chCode_verticalTab = 0x0B;           // \v


